services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.11.0
    container_name: owui
    restart: unless-stopped
    ports:
      - "3000:8080"
    volumes:
      - ./data:/app/backend/data
    environment:
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - ENABLE_OAUTH_SIGNUP=true
      - OAUTH_MERGE_ACCOUNTS_BY_EMAIL=true
      - ENABLE_LOGIN_FORM=false
      - ENABLE_PERSISTENT_CONFIG=true
      - OPENAI_API_BASE_URL=https://openrouter.ai/api/v1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OAUTH_UPDATE_PICTURE_ON_LOGIN=true
      - WEBUI_AUTH_TRUSTED_EMAIL_HEADER=Remote-Email
      - EBUI_AUTH_TRUSTED_NAME_HEADER=Remote-Name
      - WEBUI_AUTH_TRUSTED_GROUPS_HEADER=Remote-Role
      - ENABLE_OAUTH_PERSISTENT_CONFIG=false
      - TERMINAL_SERVER_CONNECTIONS=[{"id":"open-terminal","url":"http://open-terminal:8000","key":"${OPEN_TERMINAL_API_KEY}","name":"Open Terminal","auth_type":"bearer"}]
    depends_on:
      - open-terminal

  open-terminal:
    image: ghcr.io/open-webui/open-terminal:0.11.35
    container_name: open-terminal
    restart: unless-stopped
    volumes:
      - ./terminal-data:/home/user
    environment:
      - OPEN_TERMINAL_API_KEY=${OPEN_TERMINAL_API_KEY}
