services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:2.14.2
    user: "0:0"
    restart: always
    network_mode: host
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_USER_FOLDER=/home/node/.n8n
      - N8N_HOST=${LAN_IP}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_SECURE_COOKIE=false
      - NODE_ENV=production
      - WEBHOOK_URL=http://${LAN_IP}:5678/
      - GENERIC_TIMEZONE=Europe/Berlin
      - TZ=Europe/Berlin
    volumes:
      - ./data:/home/node/.n8n
      - ./files:/files
