name: donetick

services:
  app:
    image: donetick/donetick:v0.1.75
    container_name: donetick-core
    restart: unless-stopped
    init: true

    volumes:
      - ./data:/donetick-data

    ports:
      - "8085:2021"
    environment:
      DT_ENV: prod
      DT_DATABASE_TYPE: sqlite
      DT_DATABASE_MIGRATION: "true"
      DT_SQLITE_PATH: /donetick-data/donetick.db
      DT_SERVER_PORT: 2021
      DT_SERVER_SERVE_FRONTEND: "true"
      TZ: Europe/Berlin
      DT_JWT_SECRET: ${DT_JWT_SECRET}
      DT_SINGLE_CIRCLE_INSTANCE: "true"
      DT_OAUTH2_NAME: ${DT_OAUTH2_NAME}
      DT_OAUTH2_CLIENT_ID: ${DT_OAUTH2_CLIENT_ID}
      DT_OAUTH2_CLIENT_SECRET: ${DT_OAUTH2_CLIENT_SECRET}
      DT_OAUTH2_SCOPES: ${DT_OAUTH2_SCOPES}
      DT_OAUTH2_AUTH_URL: ${DT_OAUTH2_AUTH_URL}
      DT_OAUTH2_TOKEN_URL: ${DT_OAUTH2_TOKEN_URL}
      DT_OAUTH2_USER_INFO_URL: ${DT_OAUTH2_USER_INFO_URL}
      DT_OAUTH2_REDIRECT_URL: ${DT_OAUTH2_REDIRECT_URL}
      DT_OAUTH2_ADMIN_GROUPS: ${DT_OAUTH2_ADMIN_GROUPS}
      DT_OAUTH2_MANAGER_GROUPS: ${DT_OAUTH2_MANAGER_GROUPS}
    hostname: donetick-core
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:2021/api/v1/health || exit 1"]
      start_period: 1m
      timeout: 5s
      interval: 1m
      retries: 3
