services:
  broker:
    image: docker.io/library/redis:8
    restart: unless-stopped
    volumes:
      - redisdata:/data
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
      - gotenberg
      - tika
    ports:
      - "8000:8000"
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - /volume1/library/export:/usr/src/paperless/export
      - /volume1/library/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      DEBUG: true
      PAPERLESS_URL: ${PAPERLESS_URL}
  paperless-gpt:
    image: ghcr.io/icereed/paperless-gpt:latest
    environment:
      PAPERLESS_BASE_URL: "http://webserver:8000"
      PAPERLESS_API_TOKEN: ${PAPERLESS_API_TOKEN}
      PAPERLESS_PUBLIC_URL: ${PAPERLESS_URL}

      MANUAL_TAG: "paperless-gpt"
      AUTO_TAG: "paperless-gpt-auto"
      
      LLM_PROVIDER: "openai"
      LLM_MODEL: "openai/gpt-5-mini"
      OPENAI_API_KEY: ${OPENAI_API_KEY}

      OCR_PROVIDER: "llm"
      VISION_LLM_PROVIDER: "openai"
      VISION_LLM_MODEL: "openai/gpt-5-mini"

      OCR_PROCESS_MODE: "image"
      PDF_SKIP_EXISTING_OCR: "false"

      AUTO_OCR_TAG: "paperless-gpt-ocr-auto"
      OCR_LIMIT_PAGES: "0"
      LOG_LEVEL: "info"
    volumes:
      - ./prompts:/app/prompts
    ports:
      - "8010:8080"
    depends_on:
      - webserver
  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.25
    restart: unless-stopped
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
  tika:
    image: docker.io/apache/tika:latest
    restart: unless-stopped
volumes:
  data:
  media:
  redisdata: