use_default_settings:
  engines:
    keep_only:
      - duckduckgo
      - brave
      - qwant
      - wikipedia
      - wikidata
      - openstreetmap
      - arxiv
      - pubmed

general:
  debug: false
  instance_name: "SearXNG for Open WebUI"

search:
  safe_search: 2
  autocomplete: duckduckgo
  formats:
    - html
    - json

server:
  limiter: false
  image_proxy: true
