services:
  searxng:
    image: docker.io/searxng/searxng:2026.5.21-b9340f50c
    container_name: searxng
    restart: unless-stopped
    ports:
      - "8888:8080"
    environment:
      SEARXNG_PORT: "8080"
      SEARXNG_BIND_ADDRESS: "0.0.0.0"
      SEARXNG_SECRET: ${SEARXNG_SECRET}
      SEARXNG_BASE_URL: ${SEARXNG_BASE_URL}
    volumes:
      - ./core-config:/etc/searxng
      - ./data:/var/cache/searxng
